### ISSUE TITLE
Files are executable but shouldn't be

### ISSUE THREAD

**Issue by Fryguy** [IBM/ibm_power_hmc_sdk_ruby#73]
I'm seeing the following down below when we are building RPMs for infrastructure management.  What's strange is that when I pull down the source those files are _not_ marked as executable, so I'm really confused.  However, if I `gem install ibm_power_hmc`, then go to the install directory, sure enough all of the files are marked `777`

The only things I can think of are

- On whoever's machine the gem is being built they are using a non-standard way of building (Typically gems that use bundler's gem tasks use `bundle exec rake release[upstream]`)
- On whoever's machine the gem is being built the files are actually executable, but not in source
- Maybe there's a Mac vs Linux vs Windows thing going on here.

Here are the warnings:

```
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/lib/ibm_power_hmc.rb is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/lib/ibm_power_hmc/connection.rb is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/lib/ibm_power_hmc/job.rb is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/lib/ibm_power_hmc/parser.rb is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/lib/ibm_power_hmc/pcm.rb is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/lib/ibm_power_hmc/version.rb is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/.gitignore is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/.rubocop.yml is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/.rubocop_local.yml is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/CHANGELOG.md is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/Gemfile is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/LICENSE is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/README.md is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/Rakefile is executable but has no shebang, removing executable bit
*** WARNING: ./opt/IBM/infrastructure-management-gemset/gems/ibm_power_hmc-0.10.0/ibm_power_hmc.gemspec is executable but has no shebang, removing executable bit
```

**Comment by Fryguy** [comment]
cc @dberg1 @vfebvre @agrare

**Comment by jaywcarman** [comment]
I'm running Fedora, and interestingly if I set file mode for `lib/ibm_power_hmc.rb` to `777` and built the gem the file mode ended up being `755` (similar to git's behavior): 
```
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ chmod 777 lib/ibm_power_hmc.rb  
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ git diff
diff --git a/lib/ibm_power_hmc.rb b/lib/ibm_power_hmc.rb
old mode 100644
new mode 100755
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ ls -l lib/ibm_power_hmc.rb 
-rwxrwxrwx. 1 jwcarman jwcarman 346 Jun 20 08:48 lib/ibm_power_hmc.rb
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ gem build ibm_power_hmc                 
  Successfully built RubyGem
  Name: ibm_power_hmc
  Version: 0.10.0
  File: ibm_power_hmc-0.10.0.gem
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ mkdir tmp
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ tar xf ibm_power_hmc-0.10.0.gem -C ./tmp
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ tar xzf ./tmp/data.tar.gz -C ./tmp      
main|e806344 ✗|ibm_power_hmc_sdk_ruby$ ls -l ./tmp/lib 
total 4
drwxr-xr-x. 1 jwcarman jwcarman  88 Jun 20 08:49 ibm_power_hmc
-rwxr-xr-x. 1 jwcarman jwcarman 346 Jun 20 08:49 ibm_power_hmc.rb
```

**Comment by Fryguy** [comment]
That is very interesting that it removes the write bit.  I would expect it to keep the exec bit if that bit is there otherwise you can't ship _actual_ executables.

@vfebvre I still would expect `gem build` and `gem push` to work, because I'm pretty sure that's what `bundle exec rake release` does under the covers.  If this is a Windows bug I wonder if we should open an issue on rubygems itself?

**Comment by vfebvre** [comment]
I have just built & published v0.11.0, but this time on a Fedora, still with gem build/push. Permissions are set to 644 as expected.

**Comment by vfebvre** [comment]
`[padmin@pollux12 ibm_power_hmc_sdk_ruby]$ ll /home/padmin/.rvm/gems/ruby-2.7.2/gems/ibm_power_hmc-0.8.1/
total 32
drwxr-xr-x. 2 padmin padmin    34  3 févr. 15:31 bin
-rwxrwxrwx. 1 padmin padmin    26  3 févr. 15:31 CHANGELOG.md
-rwxrwxrwx. 1 padmin padmin   121  3 févr. 15:31 Gemfile
-rwxrwxrwx. 1 padmin padmin  1301  3 févr. 15:31 ibm_power_hmc.gemspec
drwxr-xr-x. 3 padmin padmin    51  3 févr. 15:31 lib
-rwxrwxrwx. 1 padmin padmin 11357  3 févr. 15:31 LICENSE
-rwxrwxrwx. 1 padmin padmin    51  3 févr. 15:31 Rakefile
-rwxrwxrwx. 1 padmin padmin  2165  3 févr. 15:31 README.md
[padmin@pollux12 ibm_power_hmc_sdk_ruby]$ ll /home/padmin/.rvm/gems/ruby-2.7.2/gems/ibm_power_hmc-0.11.0/
total 32
drwxr-xr-x. 2 padmin padmin    34  1 juil. 10:50 bin
-rw-r--r--. 1 padmin padmin    26  1 juil. 10:50 CHANGELOG.md
-rw-r--r--. 1 padmin padmin   121  1 juil. 10:50 Gemfile
-rw-r--r--. 1 padmin padmin  1363  1 juil. 10:50 ibm_power_hmc.gemspec
drwxr-xr-x. 3 padmin padmin    51  1 juil. 10:50 lib
-rw-r--r--. 1 padmin padmin 11357  1 juil. 10:50 LICENSE
-rw-r--r--. 1 padmin padmin   103  1 juil. 10:50 Rakefile
-rw-r--r--. 1 padmin padmin  2165  1 juil. 10:50 README.md
[padmin@pollux12 ibm_power_hmc_sdk_ruby]$`

**Comment by Fryguy** [comment]
Thanks @vfebvre .  I'm going to close this one.  I can confirm that on 0.11.0, the only files with exec bits are bin/setup and bin/console, which is expected.
